import { db } from '../../server/src/core/db';
import { forumCategories } from '../../shared/schema';
import { sql } from 'drizzle-orm';

export async function seedForumCategories() {
  console.log('🌱 Seeding forum categories...');

  const categoriesToSeed = [
    {
      name: 'The Pit',
      slug: 'the-pit',
      description: 'General discussion and community interaction.',
      parentId: null,
      isZone: 1,
      canonical: 1,
      position: 1,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#FF5733',
      icon: 'fire',
      colorTheme: 'theme-pit',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Announcements',
      slug: 'announcements',
      description: 'Official announcements from the staff.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 2,
      isVip: 0,
      isLocked: 1,
      minXp: 0,
      color: '#4CAF50',
      icon: 'megaphone',
      colorTheme: 'theme-announcements',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'General Discussion',
      slug: 'general-discussion',
      description: 'Talk about anything and everything.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 3,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#2196F3',
      icon: 'chat',
      colorTheme: 'theme-general',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Introductions',
      slug: 'introductions',
      description: 'New to the community? Introduce yourself here!',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 4,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#9C27B0',
      icon: 'hand-wave',
      colorTheme: 'theme-introductions',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Feedback & Suggestions',
      slug: 'feedback-suggestions',
      description: 'Share your thoughts and ideas to improve the platform.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 5,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#FFC107',
      icon: 'lightbulb',
      colorTheme: 'theme-feedback',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Bug Reports',
      slug: 'bug-reports',
      description: 'Report any bugs or technical issues you encounter.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 6,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#F44336',
      icon: 'bug',
      colorTheme: 'theme-bugs',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Off-Topic',
      slug: 'off-topic',
      description: 'Discussions that don\'t fit anywhere else.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 7,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#607D8B',
      icon: 'question',
      colorTheme: 'theme-offtopic',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Gaming',
      slug: 'gaming',
      description: 'Discuss all things gaming.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 8,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#795548',
      icon: 'gamepad',
      colorTheme: 'theme-gaming',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Technology',
      slug: 'technology',
      description: 'Latest in tech news and discussions.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 9,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#673AB7',
      icon: 'chip',
      colorTheme: 'theme-tech',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Development',
      slug: 'development',
      description: 'Coding, programming, and software development.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 10,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#00BCD4',
      icon: 'code',
      colorTheme: 'theme-dev',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Creative Corner',
      slug: 'creative-corner',
      description: 'Share your art, writing, and other creative works.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 11,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#E91E63',
      icon: 'palette',
      colorTheme: 'theme-creative',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Marketplace',
      slug: 'marketplace',
      description: 'Buy, sell, and trade within the community.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 12,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#CDDC39',
      icon: 'store',
      colorTheme: 'theme-marketplace',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Support',
      slug: 'support',
      description: 'Get help and support for platform issues.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 13,
      isVip: 0,
      isLocked: 0,
      minXp: 0,
      color: '#009688',
      icon: 'lifebuoy',
      colorTheme: 'theme-support',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Rules & Guidelines',
      slug: 'rules-guidelines',
      description: 'Important rules and guidelines for the community.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 14,
      isVip: 0,
      isLocked: 1,
      minXp: 0,
      color: '#FF9800',
      icon: 'gavel',
      colorTheme: 'theme-rules',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
    {
      name: 'Archive',
      slug: 'archive',
      description: 'Older discussions and resolved topics.',
      parentId: null,
      isZone: 0,
      canonical: 0,
      position: 15,
      isVip: 0,
      isLocked: 1,
      minXp: 0,
      color: '#757575',
      icon: 'archive',
      colorTheme: 'theme-archive',
      isHidden: 0,
      minGroupIdRequired: null,
      pluginData: '{}',
    },
  ];

  for (const categoryData of categoriesToSeed) {
    try {
      // Check if category already exists by slug
      const existingCategory = await db.select().from(forumCategories).where(sql`${forumCategories.slug} = ${categoryData.slug}`).limit(1);
      
      if (existingCategory.length === 0) {
        await db.insert(forumCategories).values(categoryData);
        console.log(`✅ Seeded category: ${categoryData.name}`);
      } else {
        console.log(`⏭️ Category already exists, skipping: ${categoryData.name}`);
      }
    } catch (error) {
      console.error(`❌ Error seeding category ${categoryData.name}:`, error);
    }
  }
  console.log('✅ Forum categories seeding complete.');
}

// Only run if this file is executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedForumCategories()
    .then(() => {
      console.log("✅ Forum category seeding complete.");
      process.exit(0);
    })
    .catch((err) => {
      console.error("❌ Forum category seeding failed:", err);
      process.exit(1);
    });
}
