import * as z from 'zod';
export declare const baseTitleSchema: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    iconUrl: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    rarity: z.ZodDefault<z.ZodEnum<["common", "uncommon", "rare", "epic", "legendary", "mythic"]>>;
    emoji: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    fontFamily: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    fontSize: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    fontWeight: z.ZodNullable<z.ZodOptional<z.ZodEnum<["normal", "bold", "bolder", "100", "200", "300", "400", "500", "600", "700", "800", "900"]>>>;
    textColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    backgroundColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    borderColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    borderWidth: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    borderStyle: z.ZodNullable<z.ZodOptional<z.ZodEnum<["solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset"]>>>;
    borderRadius: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    glowColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    glowIntensity: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shadowColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    shadowBlur: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shadowOffsetX: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shadowOffsetY: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    gradientStart: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    gradientEnd: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    gradientDirection: z.ZodNullable<z.ZodOptional<z.ZodEnum<["to-right", "to-left", "to-top", "to-bottom", "to-top-right", "to-top-left", "to-bottom-right", "to-bottom-left"]>>>;
    animation: z.ZodNullable<z.ZodOptional<z.ZodEnum<["none", "pulse", "bounce", "shake", "glow", "rainbow"]>>>;
    animationDuration: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    roleId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isShopItem: z.ZodDefault<z.ZodBoolean>;
    isUnlockable: z.ZodDefault<z.ZodBoolean>;
    unlockConditions: z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>>;
    shopPrice: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shopCurrency: z.ZodNullable<z.ZodOptional<z.ZodEnum<["DGT", "XP", "USD"]>>>;
}, "strip", z.ZodTypeAny, {
    name: string;
    rarity: "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic";
    isShopItem: boolean;
    isUnlockable: boolean;
    description?: string | null | undefined;
    textColor?: string | null | undefined;
    backgroundColor?: string | null | undefined;
    iconUrl?: string | null | undefined;
    emoji?: string | null | undefined;
    fontFamily?: string | null | undefined;
    fontSize?: number | null | undefined;
    fontWeight?: "bold" | "normal" | "bolder" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | null | undefined;
    borderColor?: string | null | undefined;
    borderWidth?: number | null | undefined;
    borderStyle?: "solid" | "dashed" | "dotted" | "double" | "groove" | "ridge" | "inset" | "outset" | null | undefined;
    borderRadius?: number | null | undefined;
    glowColor?: string | null | undefined;
    glowIntensity?: number | null | undefined;
    shadowColor?: string | null | undefined;
    shadowBlur?: number | null | undefined;
    shadowOffsetX?: number | null | undefined;
    shadowOffsetY?: number | null | undefined;
    gradientStart?: string | null | undefined;
    gradientEnd?: string | null | undefined;
    gradientDirection?: "to-right" | "to-left" | "to-top" | "to-bottom" | "to-top-right" | "to-top-left" | "to-bottom-right" | "to-bottom-left" | null | undefined;
    animation?: "bounce" | "none" | "pulse" | "shake" | "glow" | "rainbow" | null | undefined;
    animationDuration?: number | null | undefined;
    roleId?: string | null | undefined;
    unlockConditions?: Record<string, any> | null | undefined;
    shopPrice?: number | null | undefined;
    shopCurrency?: "DGT" | "XP" | "USD" | null | undefined;
}, {
    name: string;
    rarity?: "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic" | undefined;
    description?: string | null | undefined;
    textColor?: string | null | undefined;
    backgroundColor?: string | null | undefined;
    iconUrl?: string | null | undefined;
    emoji?: string | null | undefined;
    fontFamily?: string | null | undefined;
    fontSize?: number | null | undefined;
    fontWeight?: "bold" | "normal" | "bolder" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | null | undefined;
    borderColor?: string | null | undefined;
    borderWidth?: number | null | undefined;
    borderStyle?: "solid" | "dashed" | "dotted" | "double" | "groove" | "ridge" | "inset" | "outset" | null | undefined;
    borderRadius?: number | null | undefined;
    glowColor?: string | null | undefined;
    glowIntensity?: number | null | undefined;
    shadowColor?: string | null | undefined;
    shadowBlur?: number | null | undefined;
    shadowOffsetX?: number | null | undefined;
    shadowOffsetY?: number | null | undefined;
    gradientStart?: string | null | undefined;
    gradientEnd?: string | null | undefined;
    gradientDirection?: "to-right" | "to-left" | "to-top" | "to-bottom" | "to-top-right" | "to-top-left" | "to-bottom-right" | "to-bottom-left" | null | undefined;
    animation?: "bounce" | "none" | "pulse" | "shake" | "glow" | "rainbow" | null | undefined;
    animationDuration?: number | null | undefined;
    roleId?: string | null | undefined;
    isShopItem?: boolean | undefined;
    isUnlockable?: boolean | undefined;
    unlockConditions?: Record<string, any> | null | undefined;
    shopPrice?: number | null | undefined;
    shopCurrency?: "DGT" | "XP" | "USD" | null | undefined;
}>;
export declare const createTitleSchema: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    iconUrl: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    rarity: z.ZodDefault<z.ZodEnum<["common", "uncommon", "rare", "epic", "legendary", "mythic"]>>;
    emoji: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    fontFamily: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    fontSize: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    fontWeight: z.ZodNullable<z.ZodOptional<z.ZodEnum<["normal", "bold", "bolder", "100", "200", "300", "400", "500", "600", "700", "800", "900"]>>>;
    textColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    backgroundColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    borderColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    borderWidth: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    borderStyle: z.ZodNullable<z.ZodOptional<z.ZodEnum<["solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset"]>>>;
    borderRadius: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    glowColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    glowIntensity: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shadowColor: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    shadowBlur: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shadowOffsetX: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shadowOffsetY: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    gradientStart: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    gradientEnd: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    gradientDirection: z.ZodNullable<z.ZodOptional<z.ZodEnum<["to-right", "to-left", "to-top", "to-bottom", "to-top-right", "to-top-left", "to-bottom-right", "to-bottom-left"]>>>;
    animation: z.ZodNullable<z.ZodOptional<z.ZodEnum<["none", "pulse", "bounce", "shake", "glow", "rainbow"]>>>;
    animationDuration: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    roleId: z.ZodNullable<z.ZodOptional<z.ZodString>>;
    isShopItem: z.ZodDefault<z.ZodBoolean>;
    isUnlockable: z.ZodDefault<z.ZodBoolean>;
    unlockConditions: z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>>;
    shopPrice: z.ZodNullable<z.ZodOptional<z.ZodNumber>>;
    shopCurrency: z.ZodNullable<z.ZodOptional<z.ZodEnum<["DGT", "XP", "USD"]>>>;
}, "strip", z.ZodTypeAny, {
    name: string;
    rarity: "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic";
    isShopItem: boolean;
    isUnlockable: boolean;
    description?: string | null | undefined;
    textColor?: string | null | undefined;
    backgroundColor?: string | null | undefined;
    iconUrl?: string | null | undefined;
    emoji?: string | null | undefined;
    fontFamily?: string | null | undefined;
    fontSize?: number | null | undefined;
    fontWeight?: "bold" | "normal" | "bolder" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | null | undefined;
    borderColor?: string | null | undefined;
    borderWidth?: number | null | undefined;
    borderStyle?: "solid" | "dashed" | "dotted" | "double" | "groove" | "ridge" | "inset" | "outset" | null | undefined;
    borderRadius?: number | null | undefined;
    glowColor?: string | null | undefined;
    glowIntensity?: number | null | undefined;
    shadowColor?: string | null | undefined;
    shadowBlur?: number | null | undefined;
    shadowOffsetX?: number | null | undefined;
    shadowOffsetY?: number | null | undefined;
    gradientStart?: string | null | undefined;
    gradientEnd?: string | null | undefined;
    gradientDirection?: "to-right" | "to-left" | "to-top" | "to-bottom" | "to-top-right" | "to-top-left" | "to-bottom-right" | "to-bottom-left" | null | undefined;
    animation?: "bounce" | "none" | "pulse" | "shake" | "glow" | "rainbow" | null | undefined;
    animationDuration?: number | null | undefined;
    roleId?: string | null | undefined;
    unlockConditions?: Record<string, any> | null | undefined;
    shopPrice?: number | null | undefined;
    shopCurrency?: "DGT" | "XP" | "USD" | null | undefined;
}, {
    name: string;
    rarity?: "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic" | undefined;
    description?: string | null | undefined;
    textColor?: string | null | undefined;
    backgroundColor?: string | null | undefined;
    iconUrl?: string | null | undefined;
    emoji?: string | null | undefined;
    fontFamily?: string | null | undefined;
    fontSize?: number | null | undefined;
    fontWeight?: "bold" | "normal" | "bolder" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | null | undefined;
    borderColor?: string | null | undefined;
    borderWidth?: number | null | undefined;
    borderStyle?: "solid" | "dashed" | "dotted" | "double" | "groove" | "ridge" | "inset" | "outset" | null | undefined;
    borderRadius?: number | null | undefined;
    glowColor?: string | null | undefined;
    glowIntensity?: number | null | undefined;
    shadowColor?: string | null | undefined;
    shadowBlur?: number | null | undefined;
    shadowOffsetX?: number | null | undefined;
    shadowOffsetY?: number | null | undefined;
    gradientStart?: string | null | undefined;
    gradientEnd?: string | null | undefined;
    gradientDirection?: "to-right" | "to-left" | "to-top" | "to-bottom" | "to-top-right" | "to-top-left" | "to-bottom-right" | "to-bottom-left" | null | undefined;
    animation?: "bounce" | "none" | "pulse" | "shake" | "glow" | "rainbow" | null | undefined;
    animationDuration?: number | null | undefined;
    roleId?: string | null | undefined;
    isShopItem?: boolean | undefined;
    isUnlockable?: boolean | undefined;
    unlockConditions?: Record<string, any> | null | undefined;
    shopPrice?: number | null | undefined;
    shopCurrency?: "DGT" | "XP" | "USD" | null | undefined;
}>;
export declare const updateTitleSchema: z.ZodObject<{
    name: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    iconUrl: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    rarity: z.ZodOptional<z.ZodDefault<z.ZodEnum<["common", "uncommon", "rare", "epic", "legendary", "mythic"]>>>;
    emoji: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    fontFamily: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    fontSize: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    fontWeight: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<["normal", "bold", "bolder", "100", "200", "300", "400", "500", "600", "700", "800", "900"]>>>>;
    textColor: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    backgroundColor: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    borderColor: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    borderWidth: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    borderStyle: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<["solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset"]>>>>;
    borderRadius: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    glowColor: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    glowIntensity: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    shadowColor: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    shadowBlur: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    shadowOffsetX: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    shadowOffsetY: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    gradientStart: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    gradientEnd: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    gradientDirection: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<["to-right", "to-left", "to-top", "to-bottom", "to-top-right", "to-top-left", "to-bottom-right", "to-bottom-left"]>>>>;
    animation: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<["none", "pulse", "bounce", "shake", "glow", "rainbow"]>>>>;
    animationDuration: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    roleId: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodString>>>;
    isShopItem: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    isUnlockable: z.ZodOptional<z.ZodDefault<z.ZodBoolean>>;
    unlockConditions: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodRecord<z.ZodString, z.ZodAny>>>>;
    shopPrice: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodNumber>>>;
    shopCurrency: z.ZodOptional<z.ZodNullable<z.ZodOptional<z.ZodEnum<["DGT", "XP", "USD"]>>>>;
}, "strip", z.ZodTypeAny, {
    name?: string | undefined;
    rarity?: "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic" | undefined;
    description?: string | null | undefined;
    textColor?: string | null | undefined;
    backgroundColor?: string | null | undefined;
    iconUrl?: string | null | undefined;
    emoji?: string | null | undefined;
    fontFamily?: string | null | undefined;
    fontSize?: number | null | undefined;
    fontWeight?: "bold" | "normal" | "bolder" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | null | undefined;
    borderColor?: string | null | undefined;
    borderWidth?: number | null | undefined;
    borderStyle?: "solid" | "dashed" | "dotted" | "double" | "groove" | "ridge" | "inset" | "outset" | null | undefined;
    borderRadius?: number | null | undefined;
    glowColor?: string | null | undefined;
    glowIntensity?: number | null | undefined;
    shadowColor?: string | null | undefined;
    shadowBlur?: number | null | undefined;
    shadowOffsetX?: number | null | undefined;
    shadowOffsetY?: number | null | undefined;
    gradientStart?: string | null | undefined;
    gradientEnd?: string | null | undefined;
    gradientDirection?: "to-right" | "to-left" | "to-top" | "to-bottom" | "to-top-right" | "to-top-left" | "to-bottom-right" | "to-bottom-left" | null | undefined;
    animation?: "bounce" | "none" | "pulse" | "shake" | "glow" | "rainbow" | null | undefined;
    animationDuration?: number | null | undefined;
    roleId?: string | null | undefined;
    isShopItem?: boolean | undefined;
    isUnlockable?: boolean | undefined;
    unlockConditions?: Record<string, any> | null | undefined;
    shopPrice?: number | null | undefined;
    shopCurrency?: "DGT" | "XP" | "USD" | null | undefined;
}, {
    name?: string | undefined;
    rarity?: "common" | "uncommon" | "rare" | "epic" | "legendary" | "mythic" | undefined;
    description?: string | null | undefined;
    textColor?: string | null | undefined;
    backgroundColor?: string | null | undefined;
    iconUrl?: string | null | undefined;
    emoji?: string | null | undefined;
    fontFamily?: string | null | undefined;
    fontSize?: number | null | undefined;
    fontWeight?: "bold" | "normal" | "bolder" | "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | null | undefined;
    borderColor?: string | null | undefined;
    borderWidth?: number | null | undefined;
    borderStyle?: "solid" | "dashed" | "dotted" | "double" | "groove" | "ridge" | "inset" | "outset" | null | undefined;
    borderRadius?: number | null | undefined;
    glowColor?: string | null | undefined;
    glowIntensity?: number | null | undefined;
    shadowColor?: string | null | undefined;
    shadowBlur?: number | null | undefined;
    shadowOffsetX?: number | null | undefined;
    shadowOffsetY?: number | null | undefined;
    gradientStart?: string | null | undefined;
    gradientEnd?: string | null | undefined;
    gradientDirection?: "to-right" | "to-left" | "to-top" | "to-bottom" | "to-top-right" | "to-top-left" | "to-bottom-right" | "to-bottom-left" | null | undefined;
    animation?: "bounce" | "none" | "pulse" | "shake" | "glow" | "rainbow" | null | undefined;
    animationDuration?: number | null | undefined;
    roleId?: string | null | undefined;
    isShopItem?: boolean | undefined;
    isUnlockable?: boolean | undefined;
    unlockConditions?: Record<string, any> | null | undefined;
    shopPrice?: number | null | undefined;
    shopCurrency?: "DGT" | "XP" | "USD" | null | undefined;
}>;
export type CreateTitleInput = z.infer<typeof createTitleSchema>;
export type UpdateTitleInput = z.infer<typeof updateTitleSchema>;
