// Canonical Zone Registry for Degentalk
// This file defines the runtime config for all forum zones (Primary and General)

export enum ForumType {
  Primary = 'primary',
  General = 'general',
}

export enum ZoneComponent {
  Shoutbox = 'Shoutbox',
  XPTracker = 'XPTracker',
  BountyBoard = 'BountyBoard',
  Leaderboards = 'Leaderboards', // Added for Mission Control
  LiveListings = 'LiveListings', // Added for DegenShop
  // Add more as needed
}

export type ThreadRules = {
  allowUserPosts: boolean;
  requireDGT?: boolean; // Made optional as not all zones define it
  allowPolls: boolean;
  unlockedStyling?: boolean; // Made optional
  readOnly?: boolean; // Added for The Archive
};

export type AccessControl = {
  canPost: string[]; // e.g., ['admin', 'mod', 'all', 'vip']
  canReply: string[];
  canView: string[];
};

export type SEOConfig = {
  title: string;
  description: string;
  category?: string; // Added for General Zones metadata
};

export type ZoneConfig = {
  id: string;
  slug: string;
  forum_type: ForumType;
  name: string;
  description?: string;
  components: ZoneComponent[];
  threadRules: ThreadRules;
  accessControl: AccessControl;
  seo: SEOConfig;
  displayPriority: number;
  theme?: string;
  parent_id?: string;
  slug_override?: string;
  unrestrictedThreadPerMonth?: boolean; // For The Pit's special mechanic
  postingLimits?: any; // Optional for beginner zones (General)
  // Additional fields for specific zone logic can be added here
};

// Degentalk Zone Registry
export const zoneRegistry: Record<string, ZoneConfig> = {
  // --- PRIMARY ZONES ---

  'the-pit': {
    id: 'pz-001',
    slug: 'the-pit',
    forum_type: ForumType.Primary,
    name: 'The Pit',
    description: 'Raw, unfiltered, and often unhinged. The proving ground for every user, no matter how wrecked.',
    components: [ZoneComponent.Shoutbox], // Stub
    threadRules: {
      allowUserPosts: true, // Posting limit: 1 unrestricted thread per month
      allowPolls: true,
      unlockedStyling: true,
    },
    accessControl: {
      canPost: ['all'],
      canReply: ['all'],
      canView: ['all'],
    },
    seo: {
      title: 'The Pit - Degentalk',
      description: 'Raw, unfiltered, and often unhinged.',
    },
    displayPriority: 1,
    theme: 'pit-theme', // Stub
    unrestrictedThreadPerMonth: true,
  },
  'the-pit-shitposting': {
    id: 'pz-001-sf-001',
    slug: 'shitposting',
    parent_id: 'pz-001',
    forum_type: ForumType.Primary,
    name: 'Shitposting',
    description: 'Subforum of The Pit for shitposting.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true, unlockedStyling: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Shitposting - The Pit', description: 'The Pit's Shitposting Zone' },
    displayPriority: 1, // Subforum display order managed by parent or UI
  },
  'the-pit-memes': {
    id: 'pz-001-sf-002',
    slug: 'memes',
    parent_id: 'pz-001',
    forum_type: ForumType.Primary,
    name: 'Memes',
    description: 'Subforum of The Pit for memes.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true, unlockedStyling: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Memes - The Pit', description: 'The Pit's Memes Zone' },
    displayPriority: 2,
  },
  'the-pit-offtopic': {
    id: 'pz-001-sf-003',
    slug: 'offtopic',
    parent_id: 'pz-001',
    forum_type: ForumType.Primary,
    name: 'Off-Topic',
    description: 'Subforum of The Pit for off-topic discussions.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true, unlockedStyling: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Off-Topic - The Pit', description: 'The Pit's Off-Topic Zone' },
    displayPriority: 3,
  },
  'the-pit-experimental': {
    id: 'pz-001-sf-004',
    slug: 'experimental',
    parent_id: 'pz-001',
    forum_type: ForumType.Primary,
    name: 'Experimental',
    description: 'Subforum of The Pit for experimental content.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true, unlockedStyling: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Experimental - The Pit', description: 'The Pit's Experimental Zone' },
    displayPriority: 4,
  },

  'mission-control': {
    id: 'pz-002',
    slug: 'mission-control',
    forum_type: ForumType.Primary,
    name: 'Mission Control',
    description: 'Official dispatches, challenge ops, and leaderboard briefings. Controlled by Admins & Mods.',
    components: [ZoneComponent.Leaderboards, ZoneComponent.BountyBoard], // Stub
    threadRules: {
      allowUserPosts: false, // Admins + Mods only can post
      allowPolls: true, // Assuming admins might post polls
    },
    accessControl: {
      canPost: ['admin', 'mod'],
      canReply: ['all'], // Users can participate in challenges/tasks
      canView: ['all'],
    },
    seo: {
      title: 'Mission Control - Degentalk',
      description: 'Official dispatches, challenge ops, and leaderboard briefings.',
    },
    displayPriority: 2,
    theme: 'mission-theme', // Stub
  },
  'mission-control-daily-tasks': {
    id: 'pz-002-sf-001',
    slug: 'daily-tasks',
    parent_id: 'pz-002',
    forum_type: ForumType.Primary,
    name: 'Daily Tasks',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Daily Tasks - Mission Control', description: 'Daily tasks and objectives.' },
    displayPriority: 1,
  },
  'mission-control-giveaways': {
    id: 'pz-002-sf-002',
    slug: 'giveaways',
    parent_id: 'pz-002',
    forum_type: ForumType.Primary,
    name: 'Giveaways',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Giveaways - Mission Control', description: 'Official giveaways.' },
    displayPriority: 2,
  },
  'mission-control-challenges': {
    id: 'pz-002-sf-003',
    slug: 'challenges',
    parent_id: 'pz-002',
    forum_type: ForumType.Primary,
    name: 'Challenges',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Challenges - Mission Control', description: 'Community challenges.' },
    displayPriority: 3,
  },
  'mission-control-leaderboards': {
    id: 'pz-002-sf-004',
    slug: 'leaderboards',
    parent_id: 'pz-002',
    forum_type: ForumType.Primary,
    name: 'Leaderboards',
    components: [ZoneComponent.Leaderboards],
    threadRules: { allowUserPosts: false, allowPolls: false },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Leaderboards - Mission Control', description: 'Event and activity leaderboards.' },
    displayPriority: 4,
  },
  'mission-control-event-ops': {
    id: 'pz-002-sf-005',
    slug: 'event-ops',
    parent_id: 'pz-002',
    forum_type: ForumType.Primary,
    name: 'Event Ops',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Event Ops - Mission Control', description: 'Special event operations.' },
    displayPriority: 5,
  },

  'the-vault': {
    id: 'pz-003',
    slug: 'the-vault',
    forum_type: ForumType.Primary,
    name: 'The Vault',
    description: 'Access granted. Home of gated knowledge, elite polls, and inner-circle talk.',
    components: [], // Stub
    threadRules: {
      allowUserPosts: true, // Normal forum behavior, but gated
      allowPolls: true,
    },
    accessControl: {
      canPost: ['vip', 'admin', 'mod'], // Role-gated: 'vip', 'high-roller'
      canReply: ['vip', 'admin', 'mod'],
      canView: ['vip', 'admin', 'mod'],
    },
    seo: {
      title: 'The Vault - Degentalk',
      description: 'Gated knowledge, elite polls, and inner-circle talk.',
    },
    displayPriority: 3,
    theme: 'vault-theme', // Stub
  },
  'the-vault-vip-discussion': {
    id: 'pz-003-sf-001',
    slug: 'vip-discussion',
    parent_id: 'pz-003',
    forum_type: ForumType.Primary,
    name: 'VIP Discussion',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['vip', 'admin', 'mod'], canReply: ['vip', 'admin', 'mod'], canView: ['vip', 'admin', 'mod'] },
    seo: { title: 'VIP Discussion - The Vault', description: 'Discussions for VIP members.' },
    displayPriority: 1,
  },
  'the-vault-hidden-gems': {
    id: 'pz-003-sf-002',
    slug: 'hidden-gems',
    parent_id: 'pz-003',
    forum_type: ForumType.Primary,
    name: 'Hidden Gems', // Some threads marked read-only gems
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true }, // Individual threads can be read-only
    accessControl: { canPost: ['vip', 'admin', 'mod'], canReply: ['vip', 'admin', 'mod'], canView: ['vip', 'admin', 'mod'] },
    seo: { title: 'Hidden Gems - The Vault', description: 'Exclusive insights and information.' },
    displayPriority: 2,
  },
  'the-vault-alpha-only-polls': {
    id: 'pz-003-sf-003',
    slug: 'alpha-only-polls',
    parent_id: 'pz-003',
    forum_type: ForumType.Primary,
    name: 'Alpha-Only Polls',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['vip', 'admin', 'mod'], canReply: ['vip', 'admin', 'mod'], canView: ['vip', 'admin', 'mod'] },
    seo: { title: 'Alpha-Only Polls - The Vault', description: 'Polls that influence platform development.' },
    displayPriority: 3,
  },
  'the-vault-archives': {
    id: 'pz-003-sf-004',
    slug: 'vault-archives',
    parent_id: 'pz-003',
    forum_type: ForumType.Primary,
    name: 'Vault Archives',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['vip', 'admin', 'mod'], canReply: ['vip', 'admin', 'mod'], canView: ['vip', 'admin', 'mod'] },
    seo: { title: 'Vault Archives - The Vault', description: 'Archived discussions from The Vault.' },
    displayPriority: 4,
  },

  'the-briefing-room': {
    id: 'pz-004',
    slug: 'the-briefing-room',
    forum_type: ForumType.Primary,
    name: 'The Briefing Room',
    description: 'Start here. Forum rules, roadmap, onboarding guides, and staff updates.',
    components: [], // Stub
    threadRules: {
      allowUserPosts: true, // Posting allowed in select forums
      allowPolls: true,
    },
    accessControl: {
      canPost: ['all'], // Default, subforums can override
      canReply: ['all'],
      canView: ['all'],
    },
    seo: {
      title: 'The Briefing Room - Degentalk',
      description: 'Forum rules, roadmap, onboarding guides, and staff updates.',
    },
    displayPriority: 4,
    theme: 'briefing-theme', // Stub
  },
  'the-briefing-room-introductions': {
    id: 'pz-004-sf-001',
    slug: 'introductions',
    parent_id: 'pz-004',
    forum_type: ForumType.Primary,
    name: 'Introductions',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: false },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Introductions - Briefing Room', description: 'Introduce yourself to the community.' },
    displayPriority: 1,
  },
  'the-briefing-room-rules': {
    id: 'pz-004-sf-002',
    slug: 'rules',
    parent_id: 'pz-004',
    forum_type: ForumType.Primary,
    name: 'Rules',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: false, readOnly: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['admin', 'mod'], canView: ['all'] },
    seo: { title: 'Forum Rules - Briefing Room', description: 'Official Degentalk forum rules.' },
    displayPriority: 2,
  },
  'the-briefing-room-forum-features': {
    id: 'pz-004-sf-003',
    slug: 'forum-features',
    parent_id: 'pz-004',
    forum_type: ForumType.Primary,
    name: 'Forum Features',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: false, readOnly: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['admin', 'mod'], canView: ['all'] },
    seo: { title: 'Forum Features - Briefing Room', description: 'Guides on using forum features.' },
    displayPriority: 3,
  },
  'the-briefing-room-announcements': {
    id: 'pz-004-sf-004',
    slug: 'announcements',
    parent_id: 'pz-004',
    forum_type: ForumType.Primary,
    name: 'Announcements',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: false, readOnly: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['admin', 'mod'], canView: ['all'] },
    seo: { title: 'Announcements - Briefing Room', description: 'Official platform announcements.' },
    displayPriority: 4,
  },
  'the-briefing-room-roadmap': {
    id: 'pz-004-sf-005',
    slug: 'roadmap',
    parent_id: 'pz-004',
    forum_type: ForumType.Primary,
    name: 'Roadmap',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: false, readOnly: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: ['admin', 'mod'], canView: ['all'] },
    seo: { title: 'Roadmap - Briefing Room', description: 'Degentalk platform roadmap.' },
    displayPriority: 5,
  },
  'the-briefing-room-support': {
    id: 'pz-004-sf-006',
    slug: 'support',
    parent_id: 'pz-004',
    forum_type: ForumType.Primary,
    name: 'Support',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: false },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Support - Briefing Room', description: 'Get help and support.' },
    displayPriority: 6,
  },

  'the-archive': {
    id: 'pz-005',
    slug: 'the-archive',
    forum_type: ForumType.Primary,
    name: 'The Archive',
    description: 'Legendary threads frozen in time. Read-only graveyard of brilliance and wreckage.',
    components: [], // Stub
    threadRules: {
      allowUserPosts: false, // No posting, no replies
      allowPolls: false,
      readOnly: true,
    },
    accessControl: {
      canPost: ['admin', 'mod'], // Admins/mods can "archive" threads here
      canReply: [],
      canView: ['all'],
    },
    seo: {
      title: 'The Archive - Degentalk',
      description: 'Legendary threads frozen in time.',
    },
    displayPriority: 5,
    theme: 'archive-theme', // Stub
  },
  'the-archive-legendary-threads': {
    id: 'pz-005-sf-001',
    slug: 'legendary-threads',
    parent_id: 'pz-005',
    forum_type: ForumType.Primary,
    name: 'Legendary Threads',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: false, readOnly: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: [], canView: ['all'] },
    seo: { title: 'Legendary Threads - The Archive', description: 'Collection of legendary threads.' },
    displayPriority: 1,
  },
  'the-archive-hall-of-gains': {
    id: 'pz-005-sf-002',
    slug: 'hall-of-gains',
    parent_id: 'pz-005',
    forum_type: ForumType.Primary,
    name: 'Hall of Gains',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: false, readOnly: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: [], canView: ['all'] },
    seo: { title: 'Hall of Gains - The Archive', description: 'Showcase of epic gains.' },
    displayPriority: 2,
  },
  'the-archive-historic-rekt': {
    id: 'pz-005-sf-003',
    slug: 'historic-rekt',
    parent_id: 'pz-005',
    forum_type: ForumType.Primary,
    name: 'Historic Rekt',
    components: [],
    threadRules: { allowUserPosts: false, allowPolls: false, readOnly: true },
    accessControl: { canPost: ['admin', 'mod'], canReply: [], canView: ['all'] },
    seo: { title: 'Historic Rekt - The Archive', description: 'Memorable rekt stories.' },
    displayPriority: 3,
  },

  'degenshop': {
    id: 'pz-006',
    slug: 'degenshop',
    forum_type: ForumType.Primary,
    name: 'DegenShop™',
    description: 'Marketplace access, hot items, wishlist flex, and DGT-fueled cosmetics.',
    components: [ZoneComponent.LiveListings], // Connected to /shop feature logic
    threadRules: {
      allowUserPosts: true, // Assuming users can post about shop items, wishlists
      allowPolls: true,
    },
    accessControl: {
      canPost: ['all'],
      canReply: ['all'],
      canView: ['all'],
    },
    seo: {
      title: 'DegenShop™ - Degentalk',
      description: 'Marketplace for DGT-fueled cosmetics and items.',
    },
    displayPriority: 6,
    theme: 'shop-theme', // Stub
  },
  'degenshop-cosmetics': {
    id: 'pz-006-sf-001',
    slug: 'cosmetics',
    parent_id: 'pz-006',
    forum_type: ForumType.Primary,
    name: 'Cosmetics',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Cosmetics - DegenShop™', description: 'User cosmetics and appearance items.' },
    displayPriority: 1,
  },
  'degenshop-exclusive-items': {
    id: 'pz-006-sf-002',
    slug: 'exclusive-items',
    parent_id: 'pz-006',
    forum_type: ForumType.Primary,
    name: 'Exclusive Items',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Exclusive Items - DegenShop™', description: 'Rare and exclusive shop items.' },
    displayPriority: 2,
  },
  'degenshop-dgt-utility': {
    id: 'pz-006-sf-003',
    slug: 'dgt-utility',
    parent_id: 'pz-006',
    forum_type: ForumType.Primary,
    name: 'DGT Utility',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'DGT Utility - DegenShop™', description: 'Items with DGT token utility.' },
    displayPriority: 3,
  },
  'degenshop-wishlist': {
    id: 'pz-006-sf-004',
    slug: 'wishlist',
    parent_id: 'pz-006',
    forum_type: ForumType.Primary,
    name: 'Wishlist',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Wishlist - DegenShop™', description: 'User wishlists and item requests.' },
    displayPriority: 4,
  },

  // --- GENERAL ZONES ---

  'market-moves': {
    id: 'gz-001',
    slug: 'market-moves',
    forum_type: ForumType.General,
    name: 'Market Moves',
    description: 'TA, coin calls, and degenerate optimism.',
    components: [], // Stub
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Market Moves - Degentalk',
      description: 'Technical analysis, coin calls, and market discussions.',
      category: 'Trading & Investing',
    },
    displayPriority: 7, // Continuing from Primary Zones
    theme: 'general-theme', // Stub
  },
  'market-moves-signals-ta': {
    id: 'gz-001-sf-001',
    slug: 'signals-ta',
    parent_id: 'gz-001',
    forum_type: ForumType.General,
    name: 'Signals & TA',
    description: 'Charts, predictions, hopium.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Signals & TA - Market Moves', description: 'Technical analysis and trading signals.' },
    displayPriority: 1,
  },
  'market-moves-moonshots': {
    id: 'gz-001-sf-002',
    slug: 'moonshots',
    parent_id: 'gz-001',
    forum_type: ForumType.General,
    name: 'Moonshots',
    description: 'Low cap gems & 1000x dreams.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Moonshots - Market Moves', description: 'Discussions on low cap gems and potential moonshots.' },
    displayPriority: 2,
  },
  'market-moves-red-flags': {
    id: 'gz-001-sf-003',
    slug: 'red-flags',
    parent_id: 'gz-001',
    forum_type: ForumType.General,
    name: 'Red Flags',
    description: 'Scam alerts & project warnings.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Red Flags - Market Moves', description: 'Scam alerts and project warnings.' },
    displayPriority: 3,
  },

  'alpha-and-leaks': {
    id: 'gz-002',
    slug: 'alpha-and-leaks',
    forum_type: ForumType.General,
    name: 'Alpha & Leaks',
    description: 'Early plays, token gossip, and stuff you shouldn't know.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Alpha & Leaks - Degentalk',
      description: 'Exclusive alpha, token gossip, and leaks.',
      category: 'Insider Info',
    },
    displayPriority: 8,
  },
  'alpha-and-leaks-token-intel': {
    id: 'gz-002-sf-001',
    slug: 'token-intel',
    parent_id: 'gz-002',
    forum_type: ForumType.General,
    name: 'Token Intel',
    description: 'Deep dives, analysis.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Token Intel - Alpha & Leaks', description: 'In-depth token analysis and intelligence.' },
    displayPriority: 1,
  },
  'alpha-and-leaks-pre-sales': {
    id: 'gz-002-sf-002',
    slug: 'pre-sales',
    parent_id: 'gz-002',
    forum_type: ForumType.General,
    name: 'Pre-Sales',
    description: 'Whitelists, IDOs, launches.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Pre-Sales - Alpha & Leaks', description: 'Information on whitelists, IDOs, and token launches.' },
    displayPriority: 2,
  },
  'alpha-and-leaks-screenshots': {
    id: 'gz-002-sf-003',
    slug: 'screenshots',
    parent_id: 'gz-002',
    forum_type: ForumType.General,
    name: 'Screenshots',
    description: 'Leaks, DMs, "alleged" proof.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Screenshots - Alpha & Leaks', description: 'Leaked screenshots, DMs, and alleged proof.' },
    displayPriority: 3,
  },
  
  'casino-and-degen': {
    id: 'gz-003',
    slug: 'casino-and-degen',
    forum_type: ForumType.General,
    name: 'Casino & Degen',
    description: 'Wagers, rage posts, unsolicited strategies.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Casino & Degen - Degentalk',
      description: 'Discussions on crypto casinos, wagers, and degen plays.',
      category: 'Gambling',
    },
    displayPriority: 9,
  },
   'casino-and-degen-limbo-dice': {
    id: 'gz-003-sf-001',
    slug: 'limbo-dice',
    parent_id: 'gz-003',
    forum_type: ForumType.General,
    name: 'Limbo & Dice',
    description: 'Limbo, classic dice, ultimate degen.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Limbo & Dice - Casino & Degen', description: 'Discuss Limbo, Dice and other casino games.' },
    displayPriority: 1,
  },
  'casino-and-degen-mines-keno': {
    id: 'gz-003-sf-002',
    slug: 'mines-keno',
    parent_id: 'gz-003',
    forum_type: ForumType.General,
    name: 'Mines & Keno',
    description: 'For the clickers.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Mines & Keno - Casino & Degen', description: 'Discuss Mines, Keno and other clicker games.' },
    displayPriority: 2,
  },
  'casino-and-degen-rage-logs': {
    id: 'gz-003-sf-003',
    slug: 'rage-logs',
    parent_id: 'gz-003',
    forum_type: ForumType.General,
    name: 'Rage Logs',
    description: 'Losses. Vent. Cry.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Rage Logs - Casino & Degen', description: 'Vent your gambling losses and frustrations.' },
    displayPriority: 3,
  },

  'builders-terminal': {
    id: 'gz-004',
    slug: 'builders-terminal',
    forum_type: ForumType.General,
    name: 'Builder's Terminal',
    description: 'Dev logs, debugging, tool drops, and builder cope.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Builder's Terminal - Degentalk',
      description: 'A place for developers to share logs, debug, and drop tools.',
      category: 'Development',
    },
    displayPriority: 10,
  },
  'builders-terminal-dev-diaries': {
    id: 'gz-004-sf-001',
    slug: 'dev-diaries',
    parent_id: 'gz-004',
    forum_type: ForumType.General,
    name: 'Dev Diaries',
    description: 'Project journey logs.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Dev Diaries - Builder's Terminal', description: 'Share your project development journey.' },
    displayPriority: 1,
  },
  'builders-terminal-code-snippets': {
    id: 'gz-004-sf-002',
    slug: 'code-snippets',
    parent_id: 'gz-004',
    forum_type: ForumType.General,
    name: 'Code Snippets',
    description: 'Reusable code & help.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Code Snippets - Builder's Terminal', description: 'Share and find reusable code snippets.' },
    displayPriority: 2,
  },
  'builders-terminal-tool-drops': {
    id: 'gz-004-sf-003',
    slug: 'tool-drops',
    parent_id: 'gz-004',
    forum_type: ForumType.General,
    name: 'Tool Drops',
    description: 'Shill your tools, libs, APIs.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Tool Drops - Builder's Terminal', description: 'Share your development tools, libraries, and APIs.' },
    displayPriority: 3,
  },

  'airdrops-and-quests-general': { // Renamed from 'airdrops-and-quests' to avoid conflict with example
    id: 'gz-005',
    slug: 'airdrops-and-quests-general',
    forum_type: ForumType.General,
    name: 'Airdrops & Quests',
    description: 'Click. Grind. Pray. Share your links here.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Airdrops & Quests - Degentalk',
      description: 'Find and share airdrops, quests, and referral events.',
      category: 'Airdrops & Giveaways',
    },
    displayPriority: 11,
  },
  'airdrops-and-quests-general-quests-tasks': {
    id: 'gz-005-sf-001',
    slug: 'quests-tasks',
    parent_id: 'gz-005',
    forum_type: ForumType.General,
    name: 'Quests & Tasks',
    description: 'Galxe, Zealy, Layer3, etc.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Quests & Tasks - Airdrops & Quests', description: 'Share and find quests from platforms like Galxe, Zealy, Layer3.' },
    displayPriority: 1,
  },
  'airdrops-and-quests-general-claim-links': {
    id: 'gz-005-sf-002',
    slug: 'claim-links',
    parent_id: 'gz-005',
    forum_type: ForumType.General,
    name: 'Claim Links',
    description: 'Direct claims (DYOR).',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Claim Links - Airdrops & Quests', description: 'Direct claim links for airdrops (DYOR).' },
    displayPriority: 2,
  },
  'airdrops-and-quests-general-referral-events': {
    id: 'gz-005-sf-003',
    slug: 'referral-events',
    parent_id: 'gz-005',
    forum_type: ForumType.General,
    name: 'Referral Events',
    description: 'Invite-based tasks, pyramid scheming.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Referral Events - Airdrops & Quests', description: 'Share invite-based tasks and referral events.' },
    displayPriority: 3,
  },

  'web3-culture-and-news': {
    id: 'gz-006',
    slug: 'web3-culture-and-news',
    forum_type: ForumType.General,
    name: 'Web3 Culture & News',
    description: 'Drama, memes, launches, and chain wars.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Web3 Culture & News - Degentalk',
      description: 'Stay updated on Web3 drama, memes, launches, and chain wars.',
      category: 'News & Culture',
    },
    displayPriority: 12,
  },
  'web3-culture-and-news-general-news': {
    id: 'gz-006-sf-001',
    slug: 'general-news',
    parent_id: 'gz-006',
    forum_type: ForumType.General,
    name: 'General News',
    description: 'Major industry events.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'General News - Web3 Culture & News', description: 'Major Web3 industry news and events.' },
    displayPriority: 1,
  },
  'web3-culture-and-news-memes': {
    id: 'gz-006-sf-002',
    slug: 'memes-general', // avoid conflict with the-pit
    parent_id: 'gz-006',
    forum_type: ForumType.General,
    name: 'Memes',
    description: 'Dank culture bombs.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Memes - Web3 Culture & News', description: 'The latest and dankest Web3 memes.' },
    displayPriority: 2,
  },
  'web3-culture-and-news-chain-fights': {
    id: 'gz-006-sf-003',
    slug: 'chain-fights',
    parent_id: 'gz-006',
    forum_type: ForumType.General,
    name: 'Chain Fights',
    description: 'ETH vs SOL vs AVAX vs BASE vs BTC maxis (FIGHT).',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Chain Fights - Web3 Culture & News', description: 'Debates and discussions about different blockchains.' },
    displayPriority: 3,
  },

  'beginners-portal': {
    id: 'gz-007',
    slug: 'beginners-portal',
    forum_type: ForumType.General,
    name: 'Beginner's Portal',
    description: 'No stupid questions. Only bad answers.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Beginner's Portal - Degentalk',
      description: 'A friendly place for Web3 beginners to ask questions and learn.',
      category: 'Education',
    },
    postingLimits: { maxThreadsPerDay: 5 }, // Example posting limit
    displayPriority: 13,
  },
  'beginners-portal-getting-started': {
    id: 'gz-007-sf-001',
    slug: 'getting-started',
    parent_id: 'gz-007',
    forum_type: ForumType.General,
    name: 'Getting Started',
    description: 'Onboarding.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Getting Started - Beginner's Portal', description: 'Guides for getting started in Web3.' },
    displayPriority: 1,
  },
  'beginners-portal-terminology': {
    id: 'gz-007-sf-002',
    slug: 'terminology',
    parent_id: 'gz-007',
    forum_type: ForumType.General,
    name: 'Terminology',
    description: 'Definitions & acronyms.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Terminology - Beginner's Portal', description: 'Learn common Web3 terms and acronyms.' },
    displayPriority: 2,
  },
  'beginners-portal-wallets-safety': {
    id: 'gz-007-sf-003',
    slug: 'wallets-safety',
    parent_id: 'gz-007',
    forum_type: ForumType.General,
    name: 'Wallets & Safety',
    description: 'Basic OpSec, scam prevention.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Wallets & Safety - Beginner's Portal', description: 'Learn about wallet security and scam prevention.' },
    displayPriority: 3,
  },

  'shill-and-promote': {
    id: 'gz-008',
    slug: 'shill-and-promote',
    forum_type: ForumType.General,
    name: 'Shill & Promote',
    description: 'Projects, referrals, and maybe your OnlyFans.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: {
      title: 'Shill & Promote - Degentalk',
      description: 'Promote your projects, referrals, and other content.',
      category: 'Promotion',
    },
    displayPriority: 14,
  },
  'shill-and-promote-token-shills': {
    id: 'gz-008-sf-001',
    slug: 'token-shills',
    parent_id: 'gz-008',
    forum_type: ForumType.General,
    name: 'Token Shills',
    description: 'Altcoin promo threads.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Token Shills - Shill & Promote', description: 'Promote your altcoin projects.' },
    displayPriority: 1,
  },
  'shill-and-promote-casino-refs': {
    id: 'gz-008-sf-002',
    slug: 'casino-refs',
    parent_id: 'gz-008',
    forum_type: ForumType.General,
    name: 'Casino Refs',
    description: 'Gambling promos.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Casino Refs - Shill & Promote', description: 'Share your casino referral links.' },
    displayPriority: 2,
  },
  'shill-and-promote-self-promo': {
    id: 'gz-008-sf-003',
    slug: 'self-promo',
    parent_id: 'gz-008',
    forum_type: ForumType.General,
    name: 'Self-Promo',
    description: 'Content, services, personal links.',
    components: [],
    threadRules: { allowUserPosts: true, allowPolls: true },
    accessControl: { canPost: ['all'], canReply: ['all'], canView: ['all'] },
    seo: { title: 'Self-Promo - Shill & Promote', description: 'Promote your content, services, or personal links.' },
    displayPriority: 3,
  },
}; 