-- Forum schema cleanup: normalize to enum `type` and remove duplicated columns
-- Generated by migration script on 2025-06-15

-- 1. Remove boolean columns `is_zone` and `canonical` that duplicate the semantics of `type`
ALTER TABLE IF EXISTS "forum_categories"
  DROP COLUMN IF EXISTS "is_zone",
  DROP COLUMN IF EXISTS "canonical";

-- 2. Remove redundant `parent_forum_slug` field from `threads` table (now derived via join)
ALTER TABLE IF EXISTS "threads"
  DROP COLUMN IF EXISTS "parent_forum_slug";

-- NOTE: If look-ups by zone/forum need the booleans, prefer using expressions or generated columns,
-- e.g. `(type = 'zone') AS is_zone` in queries, rather than storing separate fields. 