ALTER TABLE "users" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "user_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "referrer_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "featured_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "deleted_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "deleted_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "edited_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "post_reactions" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "post_drafts" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "thread_drafts" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_thread_bookmarks" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "forum_rules" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "forum_rules" ALTER COLUMN "updated_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_rules_agreements" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "custom_emojis" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "post_likes" ALTER COLUMN "liked_by_user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "poll_votes" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "emoji_packs" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_emoji_packs" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "wallets" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "wallets" ALTER COLUMN "deleted_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "from_user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "to_user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "xp_adjustment_logs" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "xp_adjustment_logs" ALTER COLUMN "admin_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_titles" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "vaults" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "withdrawal_requests" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "withdrawal_requests" ALTER COLUMN "processed_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_commands" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "rain_events" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "post_tips" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "dgt_purchase_orders" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "dgt_economy_parameters" ALTER COLUMN "updated_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "platform_treasury_settings" ALTER COLUMN "updated_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "airdrop_records" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "xp_logs" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "orders" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_inventory" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "inventory_transactions" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "inventory_transactions" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_signature_items" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "conversations" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "conversation_participants" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "messages" ALTER COLUMN "sender_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "message_reads" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "direct_messages" ALTER COLUMN "sender_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "direct_messages" ALTER COLUMN "recipient_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "chat_rooms" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "shoutbox_messages" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "online_users" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "audit_logs" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "reported_content" ALTER COLUMN "reporter_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "reported_content" ALTER COLUMN "resolved_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "content_moderation_actions" ALTER COLUMN "moderator_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "announcements" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "admin_themes" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "site_templates" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "feature_flags" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "feature_flags" ALTER COLUMN "updated_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "seo_metadata" ALTER COLUMN "updated_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "media_library" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "media_library" ALTER COLUMN "deleted_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_achievements" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_mission_progress" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "analytics_events" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "activity_feed" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "admin_manual_airdrop_logs" ALTER COLUMN "admin_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "admin_manual_airdrop_logs" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_abuse_flags" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "cooldown_state" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "mentions_index" ALTER COLUMN "mentioning_user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "mentions_index" ALTER COLUMN "mentioned_user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "referral_sources" ALTER COLUMN "created_by" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_referrals" ALTER COLUMN "user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_referrals" ALTER COLUMN "referred_by_user_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "ui_analytics" ADD CONSTRAINT "ui_analytics_user_id_users_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ui_collections" ADD CONSTRAINT "ui_collections_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ui_quotes" ADD CONSTRAINT "ui_quotes_created_by_users_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("user_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" DROP COLUMN "uuid";