ALTER TABLE "backup_schedules" ALTER COLUMN "last_backup_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "restore_operations" ALTER COLUMN "source_backup_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "restore_operations" ALTER COLUMN "pre_restore_backup_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "sticker_usage" ALTER COLUMN "sticker_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "stickers" ALTER COLUMN "pack_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_sticker_inventory" ALTER COLUMN "sticker_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_sticker_packs" ALTER COLUMN "pack_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "levels" ALTER COLUMN "reward_title_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "levels" ALTER COLUMN "reward_badge_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "transactions" ALTER COLUMN "wallet_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_clout_log" ALTER COLUMN "achievement_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "vaults" ALTER COLUMN "lock_transaction_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "vaults" ALTER COLUMN "unlock_transaction_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "withdrawal_requests" ALTER COLUMN "transaction_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "forum_structure" ALTER COLUMN "parent_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "thread_drafts" ALTER COLUMN "structure_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "thread_drafts" ALTER COLUMN "prefix_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "structure_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "prefix_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "threads" ALTER COLUMN "solving_post_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "thread_tags" ALTER COLUMN "tag_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "active_frame_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "avatar_frame_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "primary_role_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "active_title_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "active_badge_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "role_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "roles" ALTER COLUMN "role_id" SET DEFAULT gen_random_uuid();--> statement-breakpoint
ALTER TABLE "user_roles" ALTER COLUMN "role_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "role_permissions" ALTER COLUMN "role_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_owned_frames" ALTER COLUMN "frame_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "category_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "featured_image_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "digital_file_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "products" ALTER COLUMN "frame_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "product_categories" ALTER COLUMN "image_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "product_categories" ALTER COLUMN "parent_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "inventory_transaction_links" ALTER COLUMN "inventory_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "inventory_transaction_links" ALTER COLUMN "dgt_transaction_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_inventory" ALTER COLUMN "product_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_inventory" ALTER COLUMN "transaction_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "animation_pack_items" ALTER COLUMN "pack_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "animation_pack_items" ALTER COLUMN "media_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "shoutbox_messages" ALTER COLUMN "room_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "online_users" ALTER COLUMN "room_id" SET DATA TYPE uuid;--> statement-breakpoint
ALTER TABLE "user_referrals" ALTER COLUMN "referral_source_id" SET DATA TYPE uuid;