-- 0014_forum_schema_refactor.sql
--
-- Forum Schema Refactor — drop legacy columns, clean up ENUM, add required flags
-- Generated by AI assistant 2025-06-16
--
-- NOTE: This migration is written for PostgreSQL.  All destructive operations
-- are guarded with IF EXISTS to ensure idempotency when re-running locally.
-- ---------------------------------------------------------------------------
BEGIN;

-- 1. (is_zone / canonical will be archived & dropped in 0015)

-- 2. Ensure required columns exist (add if missing) --------------------------
ALTER TABLE IF EXISTS forum_categories
  ADD COLUMN IF NOT EXISTS tipping_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS xp_multiplier  REAL    NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS plugin_data    JSONB   DEFAULT '{}'::jsonb;

-- 3. Clean up type ENUM ------------------------------------------------------
-- If a dedicated ENUM type already exists, replace invalid values.
-- Otherwise, we enforce the acceptable set via CHECK constraint.

-- Attempt to discover if column is an ENUM or TEXT
DO $$
BEGIN
  IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'forum_categories' AND column_name = 'type') = 'USER-DEFINED' THEN
    -- Column uses an ENUM.  Create a fresh ENUM and swap.
    -- Create the new ENUM if not present
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'forum_category_type_enum') THEN
      CREATE TYPE forum_category_type_enum AS ENUM ('zone', 'category', 'forum');
    END IF;

    -- Alter column to new ENUM using text cast → ENUM cast chain
    ALTER TABLE forum_categories
      ALTER COLUMN type TYPE forum_category_type_enum USING (type::text::forum_category_type_enum);
  ELSE
    -- Column is likely TEXT – enforce via check constraint (create or replace)
    ALTER TABLE forum_categories
      DROP CONSTRAINT IF EXISTS forum_categories_type_check;

    ALTER TABLE forum_categories
      ADD CONSTRAINT forum_categories_type_check CHECK (type IN ('zone','category','forum'));
  END IF;
END $$;

-- 4. Make `type` NOT NULL (safe if already set) ------------------------------
ALTER TABLE forum_categories
  ALTER COLUMN type SET NOT NULL;

-- 5. Drop parentForumSlug from threads --------------------------------------
ALTER TABLE IF EXISTS threads
  DROP COLUMN IF EXISTS parent_forum_slug;

COMMIT; 