export declare const shoutboxPositionEnum: import("drizzle-orm/pg-core").PgEnum<["sidebar-top", "sidebar-bottom", "main-top", "main-bottom", "floating"]>;
export declare const ticketStatusEnum: import("drizzle-orm/pg-core").PgEnum<["open", "pending", "resolved", "closed", "archived"]>;
export declare const transactionStatusEnum: import("drizzle-orm/pg-core").PgEnum<["pending", "confirmed", "failed", "reversed", "disputed"]>;
export declare const notificationTypeEnum: import("drizzle-orm/pg-core").PgEnum<["info", "system", "private_message", "achievement", "transaction", "post_mention", "thread_reply", "reaction", "quest_complete", "badge_awarded", "rain_received", "level_up", "tip_received", "airdrop_received", "referral_complete", "cosmetic_unlocked", "mission_complete"]>;
export declare const reactionTypeEnum: import("drizzle-orm/pg-core").PgEnum<["like", "helpful"]>;
export declare const walletStatusEnum: import("drizzle-orm/pg-core").PgEnum<["active", "frozen", "suspended"]>;
export declare const transactionTypeEnum: import("drizzle-orm/pg-core").PgEnum<["TIP", "DEPOSIT", "WITHDRAWAL", "ADMIN_ADJUST", "RAIN", "AIRDROP", "SHOP_PURCHASE", "REWARD", "REFERRAL_BONUS", "FEE", "VAULT_LOCK", "VAULT_UNLOCK"]>;
export declare const withdrawalStatusEnum: import("drizzle-orm/pg-core").PgEnum<["pending", "approved", "rejected"]>;
export declare const vaultStatusEnum: import("drizzle-orm/pg-core").PgEnum<["locked", "unlocked", "pending_unlock"]>;
import { userRoleEnum } from '../../../shared/enums/user';
export { userRoleEnum };
export declare const contentEditStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "published", "archived"]>;
export declare const contentVisibilityStatusEnum: import("drizzle-orm/pg-core").PgEnum<["draft", "published", "hidden", "shadowbanned", "archived", "deleted"]>;
export declare const mentionSourceTypeEnum: import("drizzle-orm/pg-core").PgEnum<["post", "thread", "chat"]>;
export declare const subscriptionTypeEnum: import("drizzle-orm/pg-core").PgEnum<["vip_pass", "degen_pass"]>;
export declare const subscriptionStatusEnum: import("drizzle-orm/pg-core").PgEnum<["active", "expired", "cancelled", "lifetime"]>;
export declare const cosmeticTypeEnum: import("drizzle-orm/pg-core").PgEnum<["avatar_frame", "badge", "title", "sticker", "emoji_pack", "profile_theme"]>;
export type TransactionType = (typeof transactionTypeEnum.enumValues)[number];
export type TransactionStatus = (typeof transactionStatusEnum.enumValues)[number];
export type ThreadStatus = (typeof contentVisibilityStatusEnum.enumValues)[number];
export type PostStatus = (typeof contentVisibilityStatusEnum.enumValues)[number];
export type UserRole = (typeof userRoleEnum.enumValues)[number];
export type NotificationType = (typeof notificationTypeEnum.enumValues)[number];
export type ReactionType = (typeof reactionTypeEnum.enumValues)[number];
export type WithdrawalStatus = (typeof withdrawalStatusEnum.enumValues)[number];
export type VaultStatus = (typeof vaultStatusEnum.enumValues)[number];
export type SubscriptionType = (typeof subscriptionTypeEnum.enumValues)[number];
export type SubscriptionStatus = (typeof subscriptionStatusEnum.enumValues)[number];
export type CosmeticType = (typeof cosmeticTypeEnum.enumValues)[number];
export type MentionSourceType = (typeof mentionSourceTypeEnum.enumValues)[number];
export type ContentEditStatus = (typeof contentEditStatusEnum.enumValues)[number];
export type ContentVisibilityStatus = (typeof contentVisibilityStatusEnum.enumValues)[number];
export type TicketStatus = (typeof ticketStatusEnum.enumValues)[number];
export type ShoutboxPosition = (typeof shoutboxPositionEnum.enumValues)[number];
//# sourceMappingURL=enums.d.ts.map