// New utility to generate avatar URL with graceful fallbacks
import md5 from 'blueimp-md5';

/**
 * Returns the best available avatar URL for a user.
 * Priority:
 * 1. Explicit avatarUrl
 * 2. Gravatar (if email present)
 * 3. UI-Avatars generated by username
 */
export function getAvatarUrl({
	avatarUrl,
	email,
	username
}: {
	avatarUrl?: string | null;
	email?: string | null;
	username: string;
}): string {
	if (avatarUrl) return avatarUrl;

	if (email) {
		const hash = md5(email.trim().toLowerCase());
		return `https://www.gravatar.com/avatar/${hash}?s=256&d=identicon`;
	}

	const initials = username.substring(0, 2).toUpperCase();
	return `https://ui-avatars.com/api/?name=${encodeURIComponent(initials)}&background=random&size=256`;
}
