#!/usr/bin/env sh

# Husky shell script generated by 'husky install'.
# Avoid editing. For details, see https://typicode.github.io/husky

if [ -z "$husky_skip_init" ]; then
  debug () {
    [ "${HUSKY_DEBUG}" = "true" ] && echo "husky (debug) - $*"
  }

  readonly husky_skip_init=1
  readonly hook_name="$(basename -- "$0")"
  debug "starting $hook_name..."

  readonly git_params="$*"
  export readonly husky_git_params="$*"

  sh -e "$(dirname -- "$0")/husky.sh" "$hook_name" "$git_params"
fi 