-- Create xp_action_logs table
CREATE TABLE IF NOT EXISTS "xp_action_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xp_action_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"action" text NOT NULL,
	"amount" integer NOT NULL,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Create xp_action_limits table
CREATE TABLE IF NOT EXISTS "xp_action_limits" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "xp_action_limits_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"action" text NOT NULL,
	"count" integer DEFAULT 1 NOT NULL,
	"last_awarded" timestamp DEFAULT now() NOT NULL,
	"day_started_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Add foreign key constraints
ALTER TABLE "xp_action_logs" ADD CONSTRAINT "xp_action_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "xp_action_limits" ADD CONSTRAINT "xp_action_limits_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
-- Create indexes
CREATE INDEX "idx_xp_action_logs_user_id" ON "xp_action_logs" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX "idx_xp_action_logs_action" ON "xp_action_logs" USING btree ("action");
--> statement-breakpoint
CREATE INDEX "idx_xp_action_logs_created_at" ON "xp_action_logs" USING btree ("created_at");
--> statement-breakpoint
CREATE INDEX "idx_xp_action_limits_user_id" ON "xp_action_limits" USING btree ("user_id");
--> statement-breakpoint
CREATE INDEX "idx_xp_action_limits_user_action" ON "xp_action_limits" USING btree ("user_id","action");
--> statement-breakpoint
CREATE UNIQUE INDEX "idx_xp_action_limits_user_action_unique" ON "xp_action_limits" USING btree ("user_id","action");
--> statement-breakpoint
-- Rename column in user_follows table
ALTER TABLE "user_follows" RENAME COLUMN "followee_id" TO "followed_id";
--> statement-breakpoint
-- Update index name for consistency
ALTER INDEX "followee_idx" RENAME TO "followed_idx";