-- Foreign Key Index Creation Script
-- Generated on 2025-07-21T05:39:43.077Z
-- Total indexes to create: 57

BEGIN;

CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_active_frame_id ON users(active_frame_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_avatar_frame_id ON users(avatar_frame_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_primary_role_id ON users(primary_role_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_referrer_id ON users(referrer_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_active_title_id ON users(active_title_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_active_badge_id ON users(active_badge_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_users_pinned_post_id ON users(pinned_post_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_userreferrals_referred_by_user_id ON userReferrals(referred_by_user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_userreferrals_referral_source_id ON userReferrals(referral_source_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_profileanalytics_viewer_user_id ON profileAnalytics(viewer_user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_notifications_event_log_id ON notifications(event_log_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_analyticsevents_user_id ON analyticsEvents(user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mentions_thread_id ON mentions(thread_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_mentions_post_id ON mentions(post_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_userinventory_dgt_transaction_id ON userInventory(dgt_transaction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_products_featured_image_id ON products(featured_image_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_products_digital_file_id ON products(digital_file_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_products_frame_id ON products(frame_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_productcategories_image_id ON productCategories(image_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_productcategories_parent_id ON productCategories(parent_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_shoutboxmessages_room_id ON shoutboxMessages(room_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_onlineusers_room_id ON onlineUsers(room_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_threads_prefix_id ON threads(prefix_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_threaddrafts_structure_id ON threadDrafts(structure_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_threaddrafts_prefix_id ON threadDrafts(prefix_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_structure_parent_id ON structure(parent_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_posts_reply_to_post_id ON posts(reply_to_post_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_postdrafts_thread_id ON postDrafts(thread_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_vaults_lock_transaction_id ON vaults(lock_transaction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_vaults_unlock_transaction_id ON vaults(unlock_transaction_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_usercloutlog_achievement_id ON userCloutLog(achievement_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_user_id ON transactions(user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_wallet_id ON transactions(wallet_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_from_user_id ON transactions(from_user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactions_to_user_id ON transactions(to_user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_levels_reward_title_id ON levels(reward_title_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_levels_reward_badge_id ON levels(reward_badge_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_airdropsettings_target_group_id ON airdropSettings(target_group_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_airdroprecords_user_id ON airdropRecords(user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_entries_approver_id ON entries(approver_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_stickers_pack_id ON stickers(pack_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user-promotions_moderator_id ON user-promotions(moderator_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user-promotions_user_promotion_id ON user-promotions(user_promotion_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user-promotions_booked_by_user_id ON user-promotions(booked_by_user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user-promotions_message_id ON user-promotions(message_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_targeting_campaign_id ON targeting(campaign_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_performance_thread_id ON performance(thread_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_payments_discussion_thread_id ON payments(discussion_thread_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_uiconfig_user_id ON uiConfig(user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_shoutboxconfig_user_id ON shoutboxConfig(user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_medialibrary_user_id ON mediaLibrary(user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_emailtemplates_recipient_user_id ON emailTemplates(recipient_user_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_backups_last_backup_id ON backups(last_backup_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_backups_pre_restore_backup_id ON backups(pre_restore_backup_id);
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_auditlogs_user_id ON auditLogs(user_id);

-- Analyze tables after index creation
ANALYZE users;
ANALYZE userReferrals;
ANALYZE profileAnalytics;
ANALYZE notifications;
ANALYZE analyticsEvents;
ANALYZE mentions;
ANALYZE userInventory;
ANALYZE products;
ANALYZE productCategories;
ANALYZE orders;
ANALYZE shoutboxMessages;
ANALYZE onlineUsers;
ANALYZE threads;
ANALYZE threadDrafts;
ANALYZE structure;
ANALYZE posts;
ANALYZE postDrafts;
ANALYZE vaults;
ANALYZE userCloutLog;
ANALYZE transactions;
ANALYZE levels;
ANALYZE airdropSettings;
ANALYZE airdropRecords;
ANALYZE entries;
ANALYZE stickers;
ANALYZE user-promotions;
ANALYZE targeting;
ANALYZE performance;
ANALYZE payments;
ANALYZE uiConfig;
ANALYZE shoutboxConfig;
ANALYZE mediaLibrary;
ANALYZE emailTemplates;
ANALYZE backups;
ANALYZE auditLogs;

COMMIT;
