# Dedicated Claude Code Development Environment
# Minimal, fast setup for Claude Code sessions

services:
  # PostgreSQL for Claude Code
  postgres:
    image: postgres:16-alpine
    container_name: claude-postgres
    environment:
      POSTGRES_DB: degentalk
      POSTGRES_USER: claude
      POSTGRES_PASSWORD: claude123
    volumes:
      - claude_postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - claude-net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U claude']
      interval: 5s
      timeout: 3s
      retries: 3

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: claude-redis
    ports:
      - '6379:6379'
    networks:
      - claude-net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 3

  # Claude Code Workspace
  claude:
    build:
      context: ../../
      dockerfile: docker/claude-code/Dockerfile
    container_name: claude-workspace
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://claude:claude123@postgres:5432/degentalk
      - REDIS_URL=redis://redis:6379
      - CLAUDE_WORKSPACE=true
    volumes:
      # Project source code (bind mount for real-time editing)
      - ../../:/workspace
      # Persistent data for better performance
      - claude_node_modules:/workspace/node_modules
      - claude_home:/home/claude
    ports:
      - '5173:5173' # Vite dev server
      - '5001:5001' # Express API server
    networks:
      - claude-net
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: ['bash', '-l']

volumes:
  claude_postgres:
  claude_node_modules:
  claude_home:

networks:
  claude-net:
    driver: bridge
