import { sql } from "drizzle-orm";
import { db } from '@db';
import { xpActionLogs } from "../../shared/schema";
import { logger } from "./src/core/logger";

export async function up() {
  logger.info('Running migration: Create XP action logs tables');

  await sql`
    -- Create the xp_action_logs table for tracking all XP awards from actions
    CREATE TABLE IF NOT EXISTS xp_action_logs (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
      action TEXT NOT NULL,
      amount INTEGER NOT NULL,
      metadata JSONB,
      created_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
    
    -- Create indexes for xp_action_logs
    CREATE INDEX IF NOT EXISTS idx_xp_action_logs_user_id ON xp_action_logs(user_id);
    CREATE INDEX IF NOT EXISTS idx_xp_action_logs_action ON xp_action_logs(action);
    CREATE INDEX IF NOT EXISTS idx_xp_action_logs_created_at ON xp_action_logs(created_at);
    
    -- Create the xp_action_limits table for tracking rate limits and cooldowns
    CREATE TABLE IF NOT EXISTS xp_action_limits (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
      action TEXT NOT NULL,
      count INTEGER NOT NULL DEFAULT 1,
      last_awarded TIMESTAMP NOT NULL DEFAULT NOW(),
      day_started_at TIMESTAMP NOT NULL DEFAULT NOW()
    );
    
    -- Create indexes for xp_action_limits
    CREATE INDEX IF NOT EXISTS idx_xp_action_limits_user_id ON xp_action_limits(user_id);
    CREATE INDEX IF NOT EXISTS idx_xp_action_limits_user_action ON xp_action_limits(user_id, action);
    
    -- Create unique constraint to ensure one record per user/action combination
    CREATE UNIQUE INDEX IF NOT EXISTS idx_xp_action_limits_unique ON xp_action_limits(user_id, action);
  `;
}

export async function down() {
  logger.info('Reverting migration: Create XP action logs tables');
  
  await sql`
    DROP TABLE IF EXISTS xp_action_limits;
    DROP TABLE IF EXISTS xp_action_logs;
  `;
}
