import { db } from '../db'; // Assuming this path is correct for your setup
import { sql } from 'drizzle-orm';
import { logger } from "./src/core/logger";

/**
 * Migration to add the dgt_packages table
 */
export async function up() {
  logger.info('Applying migration: Create dgt_packages table and seed default packages');
  
  // The CREATE TABLE IF NOT EXISTS handles the check, so checkTableExists is not needed here.
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS dgt_packages (
      package_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      description TEXT,
      dgt_amount BIGINT NOT NULL,
      usd_price DECIMAL(10, 2) NOT NULL,
      discount_percentage INTEGER,
      is_featured BOOLEAN NOT NULL DEFAULT FALSE,
      image_url VARCHAR(255),
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
    );
    
    -- Create indexes for better query performance
    CREATE INDEX IF NOT EXISTS idx_dgt_packages_name ON dgt_packages(name);
    CREATE INDEX IF NOT EXISTS idx_dgt_packages_active ON dgt_packages(is_active);
    CREATE INDEX IF NOT EXISTS idx_dgt_packages_featured ON dgt_packages(is_featured);
  `);
  
  // Insert some default packages
  // This assumes the table was just created or is empty. 
  // For true idempotency on data, an UPSERT or check-before-insert would be needed if re-running on existing data.
  // However, for a migration creating a new table, simple INSERT is usually fine.
  await db.execute(sql`
    INSERT INTO dgt_packages (
      name, 
      description, 
      dgt_amount, 
      usd_price, 
      discount_percentage, 
      is_featured, 
      sort_order
    ) VALUES
    (
      'Mini Pack', 
      'Perfect for casual users', 
      100000000, 
      5.99, 
      NULL, 
      FALSE, 
      1
    ),
    (
      'Standard Pack', 
      'Most popular option for active forum users', 
      500000000, 
      24.99, 
      10, 
      TRUE, 
      2
    ),
    (
      'Premium Pack', 
      'For power users and DGT collectors', 
      1500000000, 
      59.99, 
      20, 
      FALSE, 
      3
    ),
    (
      'Whale Pack', 
      'VIP package with maximum DGT tokens', 
      5000000000, 
      149.99, 
      30, 
      FALSE, 
      4
    )
    ON CONFLICT (name) DO NOTHING; -- Added ON CONFLICT to make data seeding safer if re-run
  `);
  
  logger.info('✅ Created dgt_packages table and inserted/updated default packages');
}

export async function down() {
  logger.info('Reverting migration: Drop dgt_packages table');
  await db.execute(sql`
    DROP TABLE IF EXISTS dgt_packages;
  `);
  logger.info('✅ Dropped dgt_packages table');
}

// Removed checkTableExists and migrate() call.
// If this script needs to be executable directly, similar logic to add-daily-xp-tracking.ts can be added.
