name: Verify Contributors

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ensure-contributor-listed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Changed Files
        id: changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            CONTRIBUTORS.md

      - name: Fail if CONTRIBUTORS.md not modified
        if: steps.changed.outputs.any_changed != 'true' && github.actor != 'goombas'
        run: |
          echo "❌ CONTRIBUTORS.md not modified."
          echo "If you are a new contributor, please add your name to CONTRIBUTORS.md."
          exit 1

      - name: ✅ Passed Contributor Check
        if: steps.changed.outputs.any_changed == 'true' || github.actor == 'goombas'
        run: echo "✅ CONTRIBUTORS.md check passed."
